name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Check out code
      
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
        image: shevonkrishmal/ctse_supplier
        tags: 0.0.1.RELEASE
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Install kubectl
      uses: azure/setup-kubectl@v1
      with:
       version: 'v1.21.3'
       id: install
        
    - name: Azure Kubernetes set context
      uses: Azure/aks-set-context@v1
      with:
       creds: ${{secrets.AZURE_CREDENTIALS}}
       resource-group: ctse_project_shevon
       cluster-name: ctse_project_supplier
        
    - name: Delete image to AKS
      run: |
        kubectl delete -f yamls/deployment.yaml
        kubectl delete -f yamls/service.yaml
        
        # Deploy to yaml files cluster
    - name: Deploy to Kubernetes cluster
      uses: Azure/k8s-deploy@v1
      with:

       manifests: |
         yamls/deployment.yaml
         yamls/service.yaml

       images: '${{secrets.DOCKER_USERNAME}}/shevonkrishmal/ctse_supplier:0.0.1.RELEASE'
       imagepullsecrets: docker-image-pull-secret
     
       action: deploy
  
