name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
       image: shevonkrishmal/ctse_supplier
       tags: 0.0.1.RELEASE
       registry: docker.io
       dockerfile: Dockerfile
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}
